# Welcome to Jekyll!
#

# Site settings
title: MySui
description: |
  MySui
owner: MySui Team # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: admin@mysui.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mysui.org" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/MySuiLab
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/communities/106072172000073923852
  #email: admin@mysui.org
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
